monolog:
#    handlers:
#        multiple_handler
#        type: whatfailuregroup # don't make the application crash if a logger doesn't respond
#        members:
#            - nested
#        nested:
#            type: rotating_file
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#            max_files: 10
#        console:
#            type: console
#            process_psr_3_messages: false
#            channels: ["!event", "!doctrine"]

